/**
 * Flowtype definitions for index
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.11.0
 */

declare module "deck.gl" {
  declare export {
    _CameraLight,
    COORDINATE_SYSTEM,
    Deck,
    Layer,
    CompositeLayer,
    View,
    MapView,
    FirstPersonView,
    OrbitView,
    OrbitViewState,
    OrthographicView,
    Viewport,
    WebMercatorViewport,
    Controller,
    MapController,
    OrbitController,
    FirstPersonController,
    OrthographicController,
    AttributeManager,
    picking,
    project,
    project32,
    gouraudLighting,
    phongLighting,
    shadow,
    LayerManager,
    DeckRenderer,
    log,
    TRANSITION_EVENTS,
    LinearInterpolator,
    FlyToInterpolator,
    Effect,
    LightingEffect,
    PostProcessEffect,
    AmbientLight,
    PointLight,
    DirectionalLight,
    LayerExtension,
    Tesselator,
    fp64LowPart,
    createIterable,
    RGBAColor,
    Position,
    Position2D,
    Position3D,
  } from "@deck.gl/core";

  declare export {
    ArcLayer,
    BitmapLayer,
    IconLayer,
    LineLayer,
    PointCloudLayer,
    ScatterplotLayer,
    GridCellLayer,
    ColumnLayer,
    PathLayer,
    PolygonLayer,
    SolidPolygonLayer,
    GeoJsonLayer,
    TextLayer,
  } from "@deck.gl/layers";

  declare export {
    ScreenGridLayer,
    CPUGridLayer,
    HexagonLayer,
    ContourLayer,
    GridLayer,
    GPUGridLayer,
    AGGREGATION_OPERATION,
    HeatmapLayer,
  } from "@deck.gl/aggregation-layers";

  declare export {
    GreatCircleLayer,
    S2Layer,
    H3ClusterLayer,
    H3HexagonLayer,
    TileLayer,
    TripsLayer,
    Tile3DLayer,
    TerrainLayer,
    MVTLayer,
  } from "@deck.gl/geo-layers";

  declare export {
    SimpleMeshLayer,
    ScenegraphLayer,
  } from "@deck.gl/mesh-layers";

  declare export { default, DeckGL } from "@deck.gl/react";

  declare export { DeckProps, PickInfo } from "@deck.gl/core/lib/deck";

  declare export { LayerInputHandler } from "@deck.gl/core/lib/layer";
}
