# This workflow will do a clean install of node dependencies, build the source code, run tests, and publishes to github.

name: Test and publish to GitHub

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: app

jobs:
  build_push_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          release_branches: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/build.zip
          asset_name: rf-coverage-maps.zip
          release_name: Build ${{ steps.tag_version.outputs.new_tag }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          overwrite: true
          body: Automatic build of main branch ${{ steps.tag_version.outputs.changelog }}
